Add euro
EgorovM/autofinder pull request #5
Opened 2022-08-09 17:53 UTC by NikitaSemenov1

2022-08-09 19:54 UTC, NikitaSemenov1 commented on main/urls.py
> +router.register('euro-faq', EuroFAQuestionViewSet)
Не стал использовать фильтр, потому что, видимо, router.register не умеет передавать параметры к view, а менять логику с роутеров на обычный path я не стал

2022-08-10 00:43 UTC, EgorovM requested changes

2022-08-10 00:43 UTC, EgorovM commented on main/urls.py
> +    LocalFAQuestionViewSet, EuroFAQuestionViewSet,
в две отдельных строки

2022-08-10 00:43 UTC, EgorovM commented on main/urls.py
> +router.register('euro-faq', EuroFAQuestionViewSet)
добавишь тогда eurofaqservices eurofaqworkexample?

2022-08-10 00:43 UTC, EgorovM commented on main/urls.py
> +router.register('euro-faq', EuroFAQuestionViewSet)
filter работает с роутерами, тебе в любом случае предстоит как нибудь с фильтрами разобраться)
но давай тогда в другом проекте

2022-08-10 13:25 UTC, EgorovM approved these changes
Локальный поменять на Автоподбор и все ок

2022-08-10 13:38 UTC, merged