Калькулятор растаможки
EgorovM/autofinder pull request #7
Opened 2022-08-13 19:08 UTC by NikitaSemenov1

2022-08-13 22:53 UTC, EgorovM requested changes

2022-08-13 22:53 UTC, EgorovM commented on main/views.py
> +class CalcRastamozhka(views.APIView):
обычно добавляют суффикс View, тип CalcRastamozhkaView
Но в любом случае не стоит латино-кириллицей писать, а сделать нормальный перевод)

2022-08-13 22:53 UTC, EgorovM commented on main/views.py
> +        response_data = _send_form(data)
если мы этот _send_form используем только для подсчета растомажовки, то почему бы его не сделать методом класса этого view?

2022-08-13 22:53 UTC, EgorovM commented on main/views.py
> +    # raise ХЗ
чекни метод raise_for_status() в requests

2022-08-13 22:53 UTC, EgorovM commented on main/views.py
> +            raise django.core.exceptions.BadRequest
Добавь причину, почему BadRequest. Что-то типа https://calcus.ru/rastamozhka-auto не отвечает

2022-08-13 22:53 UTC, EgorovM commented on main/urls.py
> +    path('calc_rastamozhka/', CalcRastamozhka.as_view())
calc_rastamozhka/ тоже стоит по другому назвать

2022-08-14 00:04 UTC, EgorovM commented on main/views.py
> +        data = request.data.dict()
напиши в комментариях к классу какие поля ожидаешь, а то непонятно

2022-08-14 06:57 UTC, EgorovM approved these changes
все супер, можно заливать)

2022-08-14 06:57 UTC, NikitaSemenov1 commented
Он еще может возвращать 
{
    'errors': { ... }
}

Так оставить или как bad request обработать?

2022-08-14 07:03 UTC, EgorovM approved these changes

2022-08-14 07:04 UTC, merged