Каталог
EgorovM/autofinder pull request #8
Opened 2022-08-13 19:46 UTC by NikitaSemenov1

2022-08-13 22:54 UTC, EgorovM commented
Добавь миграции

2022-08-13 22:55 UTC, EgorovM commented
Еще нужно будет apiview разработать, потом к нему прикручим фильтры следующим либо в этом PR

2022-08-15 17:09 UTC, NikitaSemenov1 commented
> Добавь миграции

Не понял

2022-08-15 20:25 UTC, EgorovM commented on main/models.py
> +class CarFilterRange(models.Model):
давай добавим текстовое описание, чтобы они руками могли писать их

2022-08-15 20:32 UTC, EgorovM requested changes
Нужно будет еще миграции накатить по новым моделям и полям

2022-08-15 20:32 UTC, EgorovM commented on config/settings.py
> +    'django_filters',
я обычно импортирую сторонние библиотеки первыми, а потом только свои
(давай main.apps.MainConfig ипортируем после django_filters)

2022-08-15 20:32 UTC, EgorovM commented on main/models.py
> +    description = models.TextField(verbose_name='Описание')
description лучше сделать как в class Blog. richtextfield

2022-08-15 20:32 UTC, EgorovM commented on main/models.py
> +    image = models.ImageField(verbose_name='Изображение', upload_to='car_images')
помимо него будут еще 4 фотки и одно необязтальное поле видео из ютуба (ссылка на видео)
итого нужно добавить еще 5 полей

2022-08-15 20:32 UTC, EgorovM commented on main/views.py
> +    pagination_class = None
выглядит так, будто он супер лишний

2022-08-15 20:32 UTC, EgorovM commented on main/serializers.py
> +class CarSerializer(serializers.ModelSerializer):
давай price будем приводить к такому виду: "2 000 000"

2022-08-15 20:37 UTC, EgorovM commented
И еще какие то конфликты возникли

2022-08-16 01:45 UTC, EgorovM commented on main/views.py
> +class CarViewSet(viewsets.ReadOnlyModelViewSet, mixins.ListModelMixin, viewsets.GenericViewSet):
мне кажется лишним mixins.ListModelMixin, viewsets.GenericViewSet

2022-08-17 02:47 UTC, EgorovM approved these changes

2022-08-17 02:48 UTC, merged